### ISSUE TITLE
NDEFWriter is undefined

### ISSUE THREAD

**Issue by beaufortfrancois** [federicoInserra/Big-Project-IoT#1]
NDEFWriter has been merged into NDEFReader.
The only change you'd need is something like below in https://github.com/federicoInserra/Big-Project-IoT/blob/master/3rdDelivery/webnfc/webnfc.js
```diff
-    const writer = new NDEFWriter();
+    const writer = new NDEFReader();
```

@lrazovic

**Comment by lrazovic** [comment]
Hi @beaufortfrancois, thank you for the update on the status of the Web NFC API. Cheers!
